### ISSUE TITLE
please add me as collaborator

### ISSUE THREAD

**Issue by NStift** [cr-workshop-exercises/centralized-workflow-exercise#1]
I would like tp collaborate on first exercise on Thursday morning (24.03.2022).
Thanks!

**Comment by jularina** [comment]
I would like tp collaborate on first exercise on Thursday morning (24.03.2022).
Thanks!

**Comment by bast** [comment]
Both added. You got an invite email from GitHub. Please accept that one.

**Comment by NStift** [comment]
Thanks
    On Thursday, March 24, 2022, 08:30:43 AM GMT+1, Radovan Bast ***@***.***> wrote:  
 
 


Both added. You got an invite email from GitHub. Please accept that one.
